### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by xCraimax** [TJC-Team/Seitenleiste#2]
Hallo, als ich die Seitenleiste eingestellt habe wird diese nicht angezeigt. Sie blinkt nur kurz auf und verschwindet danach wieder. (in obs)

Im Browser (Chrome) wird jedoch alles richtig angezeigt und man kann sie auch steuern.

**Comment by TheJSCode** [comment]
Ich habe das selbe Problem. Meinst du im Browser im Stream oder auf der .html Datei?

**Comment by xCraimax** [comment]
Das habe ich schon behoben bekommen. Das Problem war in OBS und zwar musst du da bei den Einstellungen vom Browser in OBS unten irgendwas mit rgb und so entfernen. Dann sollte das funktionieren

**Comment by TheJSCode** [comment]
Aha, ok..?

**Comment by TheJSCode** [comment]
Wie sieht das bei Streamlabs OBS aus?
